package cover

import "html/template"

var coverBridgeTmpl = template.Must(template.New("coverBridge").Parse(coverBridge))

const coverBridge = `
// Code generated by goc system. DO NOT EDIT.

package main

import _ "{{.CoverImportPath}}"
`

var coverMainTmpl = template.Must(template.New("coverMain").Parse(coverMain))

const coverMain = `
// Code generated by goc system. DO NOT EDIT.

package cover

import (
	"log"

	_cover "{{.GlobalCoverVarImportPath}}"
)

func init() {
	log.Println("hhhh")
}
`
