package cover

import (
	_ "embed"
	"text/template"
)

var coverBridgeTmpl = template.Must(template.New("coverBridge").Parse(coverBridge))

const coverBridge = `
// Code generated by goc system. DO NOT EDIT.

package main

import _ "{{.CoverImportPath}}"
`

var coverMainTmpl = template.Must(template.New("coverMain").Parse(coverMain))

//go:embed agent.tpl
var coverMain string

var coverWatchTmpl = template.Must(template.New("coverWatch").Parse(coverWatch))

//go:embed agentwatch.tpl
var coverWatch string
