package cover

import "html/template"

var coverBridgeTmpl = template.Must(template.New("coverBridge").Parse(coverBridge))

const coverBridge = `
// Code generated by goc system. DO NOT EDIT.

package main

import _ {{.CoverImportPath | printf "%q"}}
`

var coverMainTmpl = template.Must(template.New("coverMain").Parse(coverMain))

const coverMain = `
// Code generated by goc system. DO NOT EDIT.

package {{.Package | printf ".%q"}}

import (
	"log"

	_cover {{.GlobalCoverVarImportPath | printf "%q"}}
)

func init() {
	log.Println("hhhh")
}
`
